<?php


namespace backend\modules\core\controllers;


use backend\modules\auth\Acl;
use backend\modules\core\Constants;
use backend\modules\core\models\AnimalEvent;
use backend\modules\core\models\Organization;

class EventListController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->resource = Constants::RES_ANIMAL_EVENTS;
    }

    public function actionIndex($org_id = null)
    {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $events = AnimalEvent::eventTypeOptions();
        $country = Organization::findOne(['id' => $org_id]);
        return $this->render('/animal-event/event-lists', [
            'country' => $country,
            'events' => $events,
            'org_id' => $org_id,
        ]);
    }
}